using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity.ModelConfiguration.Conventions;
using System.Data.Entity;
using PeopleSearchWebApplication.Models;

namespace PeopleSearchWebApplication.DAL
{
    public class PeopleContext : DbContext
    {

        public PeopleContext() : base("PeopleContex")
        {
            // Code to trace SQL generated by the Entity Framework
            this.Database.Log = s => System.Diagnostics.Debug.WriteLine(s);
        }

        public DbSet<Person> Person { get; set; }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Conventions.Remove<PluralizingTableNameConvention>();
            modelBuilder.Entity<Person>().ToTable("Person");
        }

    }
}